Repository snek-shipyard/watch, pull requests merged in 2021-01, with the labels that each got.

#10 007 add track upload to next
  package.json
  src/components/molecules/tables/TrackTable/index.tsx
  src/components/organisms/modals/TrackModal/index.tsx
  src/components/organisms/modals/index.ts
  src/components/organisms/services/ohrwurm/index.tsx
  src/global.d.ts
  src/store/types.ts
Labels: dif/medium, effort/hours, kind/enhancement

#11 008 add backend integration
  src/components/organisms/modals/MemberModal/index.tsx
  src/components/organisms/modals/ProjectModal/index.tsx
  src/components/organisms/modals/TrackModal/index.tsx
  src/components/organisms/services/ohrwurm/index.tsx
  src/store/actions/ohrwurmActions.ts
  src/store/reducers/ohrwurmReducers.ts
  src/store/types.ts
Labels: dif/hard, effort/hours, kind/enhancement

#12 007 improve track upload to next
  .eslintcache
  package.json
  src/components/molecules/tables/TrackTable/index.tsx
  src/components/organisms/modals/TrackModal/index.tsx
  src/components/organisms/modals/TrackModal/trackmodal.scss
  src/components/organisms/services/ohrwurm/index.tsx
  src/store/actions/ohrwurmActions.ts
  src/store/reducers/ohrwurmReducers.ts
  src/store/types.ts
Labels: dif/easy, effort/hours, kind/enhancement

#13 008 integrate member project actions UI to next
  src/App.tsx
  src/Routes.tsx
  src/components/molecules/tables/MemberTable/index.tsx
  src/components/organisms/Navbar/index.tsx
  src/components/organisms/modals/MemberModal/index.tsx
  src/components/organisms/modals/ProjectModal/index.tsx
  src/components/organisms/services/ohrwurm/index.tsx
  src/components/pages/ohrwurm/MemberPage/index.tsx
  src/components/pages/ohrwurm/index.tsx
  src/store/actions/ohrwurmActions.ts
  src/store/types.ts
Labels: dif/easy, effort/hours, kind/enhancement
